language: r
sudo: false
cache: packages
r: devel

r_github_packages:
  - jimhester/covr
  - stan-dev/rstan/rstan/rstan@develop

notifications:
  email:
    on_success: change
    on_failure: change

warnings_are_errors: false
