language: r
sudo: false
r: devel

r_github_packages:
  - jimhester/covr
  - stan-dev/rstan/rstan/rstan@develop

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
