language: r
sudo: false
cache: packages
r: devel

env:
   global:
     - CRAN: http://cran.rstudio.com
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

r_github_packages:
  - jimhester/covr
  - stan-dev/rstan/rstan/rstan@develop

notifications:
  email:
    on_success: change
    on_failure: change

warnings_are_errors: false
